import React from 'react';
import MultiSelect from "react-multi-select-component";

export default function SelectCities(props) {

    const allCities = [
        "Anchorage, AK",
        "Birmingham, AL",
        "Huntsville, AL",
        "Montgomery, AL",
        "Mobile, AL",
        "Tuscaloosa, AL",
        "Little Rock, AR",
        "Phoenix, AZ",
        "Tucson, AZ",
        "Mesa, AZ",
        "Chandler, AZ",
        "Scottsdale, AZ",
        "Gilbert, AZ",
        "Glendale, AZ",
        "Tempe, AZ",
        "Peoria, AZ",
        "Surprise, AZ",
        "Los Angeles, CA",
        "San Diego, CA",
        "San Jose, CA",
        "San Francisco, CA",
        "Fresno, CA",
        "Sacramento, CA",
        "Long Beach, CA",
        "Oakland, CA",
        "Bakersfield, CA",
        "Anaheim, CA",
        "Santa Ana, CA",
        "Riverside, CA",
        "Stockton, CA",
        "Irvine, CA",
        "Chula Vista, CA",
        "Fremont, CA",
        "San Bernardino, CA",
        "Modesto, CA",
        "Fontana, CA",
        "Moreno Valley, CA",
        "Santa Clarita, CA",
        "Oxnard, CA",
        "Glendale, CA",
        "Huntington Beach, CA",
        "Ontario, CA",
        "Rancho Cucamonga, CA",
        "Santa Rosa, CA",
        "Oceanside, CA",
        "Elk Grove, CA",
        "Garden Grove, CA",
        "Corona, CA",
        "Hayward, CA",
        "Lancaster, CA",
        "Salinas, CA",
        "Palmdale, CA",
        "Sunnyvale, CA",
        "Pomona, CA",
        "Escondido, CA",
        "Torrance, CA",
        "Roseville, CA",
        "Pasadena, CA",
        "Orange, CA",
        "Fullerton, CA",
        "Visalia, CA",
        "Santa Clara, CA",
        "Concord, CA",
        "Thousand Oaks, CA",
        "Simi Valley, CA",
        "Victorville, CA",
        "Vallejo, CA",
        "Berkeley, CA",
        "Fairfield, CA",
        "Murrieta, CA",
        "El Monte, CA",
        "Carlsbad, CA",
        "Temecula, CA",
        "Clovis, CA",
        "Costa Mesa, CA",
        "Antioch, CA",
        "Downey, CA",
        "Richmond, CA",
        "Jurupa Valley, CA",
        "San Buenaventura (Ventura), CA",
        "Inglewood, CA",
        "Santa Maria, CA",
        "Daly City, CA",
        "West Covina, CA",
        "San Mateo, CA",
        "Norwalk, CA",
        "Rialto, CA",
        "Chico, CA",
        "El Cajon, CA",
        "Burbank, CA",
        "Vista, CA",
        "Vacaville, CA",
        "Denver, CO",
        "Colorado Springs, CO",
        "Aurora, CO",
        "Fort Collins, CO",
        "Lakewood, CO",
        "Thornton, CO",
        "Arvada, CO",
        "Westminster, CO",
        "Pueblo, CO",
        "Centennial, CO",
        "Greeley, CO",
        "Boulder, CO",
        "Bridgeport, CT",
        "New Haven, CT",
        "Stamford, CT",
        "Hartford, CT",
        "Waterbury, CT",
        "Washington, DC",
        "Jacksonville, FL",
        "Miami, FL",
        "Tampa, FL",
        "Orlando, FL",
        "St. Petersburg, FL",
        "Hialeah, FL",
        "Port St. Lucie, FL",
        "Tallahassee, FL",
        "Cape Coral, FL",
        "Fort Lauderdale, FL",
        "Pembroke Pines, FL",
        "Hollywood, FL",
        "Miramar, FL",
        "Gainesville, FL",
        "Coral Springs, FL",
        "Clearwater, FL",
        "Palm Bay, FL",
        "Lakeland, FL",
        "Pompano Beach, FL",
        "West Palm Beach, FL",
        "Miami Gardens, FL",
        "Davie, FL",
        "Atlanta, GA",
        "Augusta, GA",
        "Columbus, GA",
        "Macon, GA",
        "Savannah, GA",
        "Athens, GA",
        "Sandy Springs, GA",
        "Honolulu, HI",
        "Des Moines, IA",
        "Cedar Rapids, IA",
        "Davenport, IA",
        "Boise City, ID",
        "Meridian, ID",
        "Chicago, IL",
        "Aurora, IL",
        "Naperville, IL",
        "Joliet, IL",
        "Rockford, IL",
        "Springfield, IL",
        "Elgin, IL",
        "Peoria, IL",
        "Indianapolis, IN",
        "Fort Wayne, IN",
        "Evansville, IN",
        "South Bend, IN",
        "Carmel, IN",
        "Wichita, KS",
        "Overland Park, KS",
        "Kansas City, KS",
        "Olathe, KS",
        "Topeka, KS",
        "Louisville, KY",
        "Lexington, KY",
        "New Orleans, LA",
        "Baton Rouge, LA",
        "Shreveport, LA",
        "Lafayette, LA",
        "Boston, MA",
        "Worcester, MA",
        "Springfield, MA",
        "Cambridge, MA",
        "Lowell, MA",
        "Baltimore, MD",
        "Detroit, MI",
        "Grand Rapids, MI",
        "Warren, MI",
        "Sterling Heights, MI",
        "Ann Arbor, MI",
        "Lansing, MI",
        "Minneapolis, MN",
        "St. Paul, MN",
        "Rochester, MN",
        "Kansas City, MO",
        "St. Louis, MO",
        "Springfield, MO",
        "Columbia, MO",
        "Independence, MO",
        "Jackson, MS",
        "Billings, MT",
        "Charlotte, NC",
        "Raleigh, NC",
        "Greensboro, NC",
        "Durham, NC",
        "Winston-Salem, NC",
        "Fayetteville, NC",
        "Cary, NC",
        "Wilmington, NC",
        "High Point, NC",
        "Fargo, ND",
        "Omaha, NE",
        "Lincoln, NE",
        "Manchester, NH",
        "Newark, NJ",
        "Jersey City, NJ",
        "Paterson, NJ",
        "Elizabeth, NJ",
        "Albuquerque, NM",
        "Las Cruces, NM",
        "Las Vegas, NV",
        "Henderson, NV",
        "Reno, NV",
        "North Las Vegas, NV",
        "Sparks, NV",
        "New York, NY",
        "Buffalo, NY",
        "Rochester, NY",
        "Yonkers, NY",
        "Syracuse, NY",
        "Columbus, OH",
        "Cleveland, OH",
        "Cincinnati, OH",
        "Toledo, OH",
        "Akron, OH",
        "Dayton, OH",
        "Oklahoma City, OK",
        "Tulsa, OK",
        "Norman, OK",
        "Broken Arrow, OK",
        "Portland, OR",
        "Salem, OR",
        "Eugene, OR",
        "Gresham, OR",
        "Hillsboro, OR",
        "Bend, OR",
        "Philadelphia, PA",
        "Pittsburgh, PA",
        "Allentown, PA",
        "Providence, RI",
        "Charleston, SC",
        "Columbia, SC",
        "North Charleston, SC",
        "Sioux Falls, SD",
        "Nashville, TN",
        "Memphis, TN",
        "Knoxville, TN",
        "Chattanooga, TN",
        "Clarksville, TN",
        "Murfreesboro, TN",
        "Houston, TX",
        "San Antonio, TX",
        "Dallas, TX",
        "Austin, TX",
        "Fort Worth, TX",
        "El Paso, TX",
        "Arlington, TX",
        "Corpus Christi, TX",
        "Plano, TX",
        "Laredo, TX",
        "Lubbock, TX",
        "Garland, TX",
        "Irving, TX",
        "Frisco, TX",
        "Amarillo, TX",
        "McKinney, TX",
        "Grand Prairie, TX",
        "Brownsville, TX",
        "Killeen, TX",
        "Pasadena, TX",
        "Midland, TX",
        "McAllen, TX",
        "Denton, TX",
        "Mesquite, TX",
        "Carrollton, TX",
        "Waco, TX",
        "Round Rock, TX",
        "Abilene, TX",
        "Odessa, TX",
        "Pearland, TX",
        "Richardson, TX",
        "Sugar Land, TX",
        "College Station, TX",
        "Beaumont, TX",
        "Lewisville, TX",
        "League City, TX",
        "Tyler, TX",
        "Allen, TX",
        "Wichita Falls, TX",
        "Edinburg , TX",
        "San Angelo, TX",
        "Salt Lake City, UT",
        "West Valley City, UT",
        "Provo, UT",
        "West Jordan, UT",
        "Virginia Beach, VA",
        "Chesapeake, VA",
        "Norfolk, VA",
        "Richmond, VA",
        "Newport News, VA",
        "Alexandria, VA",
        "Hampton, VA",
        "Seattle, WA",
        "Spokane, WA",
        "Tacoma, WA",
        "Vancouver, WA",
        "Bellevue, WA",
        "Kent, WA",
        "Everett, WA",
        "Renton, WA",
        "Spokane Valley, WA",
        "Milwaukee, WI",
        "Madison, WI",
        "Green Bay, WI"    
    ]

    console.log(props.selectedStates)
    const filteredCities = []
        for (let i = 0; i < allCities.length; i++){
            let cityState = allCities[i].slice(-2)
            console.log(cityState)
            for (let j = 0; j < props.selectedStates.length; j++){
                // console.log(props.selectedStates[j])
                if (props.selectedStates[j]['value'] == cityState) filteredCities.push(allCities[i])

            }
        }

    // allCities.filter(city => {
    //             props.selectedStates.includes(city.slice(-2))
    //         }
    //     )

    console.log(filteredCities)
    
    const options = () => {
        const arr = []

        for (let i = 0; i < filteredCities.length; i++){
            let cityObj = new Object()
            cityObj["value"] = `${filteredCities[i]}`
            cityObj["label"] = `${filteredCities[i]}`
            arr.push(cityObj)
        }
        
        return arr
    }
    
    return (
        <div>
            <h4>Please select all cities that you lend in</h4>
            <MultiSelect
                options={options}
                value={props.selectedCities}
                onChange={props.setSelectedCities}
                labelledBy="Select"
            />
        </div>
    )
}
